name: CI

on:
  pull_request:
    branches-ignore:
      - 'changeset-release/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Main Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Setup local Turbo cache
        uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Use app-config.example.yaml
        run: rm app-config.yaml && mv app-config.example.yaml app-config.yaml

      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Prettier
        run: |
          yarn run prettier:check

      - name: CI
        run: yarn run ci

      - name: Check Changeset
        run: |
          yarn changeset status --since=origin/main
